version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: javax:javaee-api
    versions:
    - "> 7.0"
  - dependency-name: org.jboss:jboss-parent
    versions:
    - "37"
